### ISSUE TITLE
文件不全

### ISSUE THREAD

**Issue by luckxiao520** [Hatcat123/PortScan#1]
No module named 'scan_tools.lib'，scan_tools下缺少lib目录

**Comment by Hatcat123** [comment]
需要安装工具。namp  masscan

**Comment by luckxiao520** [comment]
感谢回复，安装工具了解的，问题是AssetScan.py中的第5行from scan_tools.lib.alive import unixping,winping和run.py中的125行from scan_tools.lib import icmp, alive,arp_scan，均有使用scan_tools.lib，然后scan_tools目录中并没有lib目录。

**Comment by Hatcat123** [comment]
卧槽！ignore文件把lib文件夹忽略了。上班后我找下项目重新上传更新

**Comment by luckxiao520** [comment]
有劳大佬得空更新下吧

**Comment by Hatcat123** [comment]
已经更新
